### ISSUE TITLE
Get Alot of errors after "pod install" #1

### ISSUE THREAD

**Issue by namuthan** [kevin-hirsch/DropDown#15]
So I added 
pod 'DropDown'

to the pod file and I ran 
$ pod install

I get all sort of errors, Please look at the screen shot.

![screen shot 2016-04-19 at 12 10 29 am](https://cloud.githubusercontent.com/assets/6484468/14629559/cf5fccd4-05c4-11e6-8249-9daae2e2b03b.png)

**Comment by kevin-hirsch** [comment]
Hello @namuthan !

DropDown is compatible for Swift 2.2 and it seems you are using a previous version of Swift which does not support things like `#selector`. You can simply update to Xcode 7.3 or use this commit 457fba9fcb693c14dbb2c45c6512f8122a19609f which is the one supporting Swift 2.1. `pod 'DropDown', :commit => '457fba9'`

**Comment by namuthan** [comment]
Thanks Kevin, 

It worked. here is what I added to the podfile

`pod 'DropDown', :git => 'https://github.com/kevin-hirsch/DropDown.git', :commit=> '457fba9fcb693c14dbb2c45c6512f8122a19609f'`

**Comment by kevin-hirsch** [comment]
Great ! I'm closing this issue.
