### ISSUE TITLE
Does not work in XCode 7

### ISSUE THREAD

**Issue by tulioht** [kevin-hirsch/DropDown#2]
Please upgrade to work with the new XCode 7 and Swift 2.0

Thanks

**Comment by kevin-hirsch** [comment]
I will do that this Saturday ;)

**Comment by kevin-hirsch** [comment]
Hey @tulioht,

The code has been upgraded to Swift 2.0 and is currently available on the develop branch ;)
I will merge it to master tomorrow and bump the Cocoapods version.

**Comment by kevin-hirsch** [comment]
It's now fixed and merged to the master. Available via Cocoapods version 0.1.4 ;)
