### ISSUE TITLE
Show Dropdown in objective-c

### ISSUE THREAD

**Issue by sagar-vaholiya** [kevin-hirsch/DropDown#9]
I tried but there error while using **show** method with dropdown object in objective-c.

how can i **call show** method for display dropdown in objective-c?

**Comment by kevin-hirsch** [comment]
Hello @sagar-vaholiya,

Thanks for using `DropDown`!
Unfortunately, `DropDown` was not made to be compatible with Objective-C. The reason the `show` method cannot be converted from Swift to Objective-C is that the method returns a tuple and tuples are a Swift only feature:

```swift
public func show() -> (canBeDisplayed: Bool, offscreenHeight: CGFloat?)
```

Nonetheless, it seems like the `show` method is the only problem for Objective-C compatibility. I could do something like:

```swift
@objc(show)
public func objc_show() {
	show()
}
```

So you could have a `show` method in Objective-C calling the `show` Swift method. The only problem is that you will miss the 2 parameters `canBeDisplayed` and `offscreenHeight`. But I could return a NSDictionary with two `NSNumber`s representing these values. 

What do you think? :)

**Comment by sagar-vaholiya** [comment]
Thank you for your complement.
Yes, it's working.
But, what about other functionality such as "selectionAction"?

`dropDown.selectionAction = { [unowned self] (index, item) in
			self.actionButton.setTitle(item, forState: .Normal)
		}`

i think, you have to make complete Objective-C version for it.

**Comment by kevin-hirsch** [comment]
The converted Objective-C code I have does contain the `selectionAction`:
```objc
@property (nonatomic, copy) void (^ __nullable selectionAction)(NSInteger, NSString * __nonnull);
```

And so I can use it like this:
```objc
DropDown *dropDown = [[DropDown alloc] init];
dropDown.selectionAction = ^(NSInteger, NSString * _Nonnull) {
	//code
};
```

You can't use this line of code above without getting an error?

**Comment by sagar-vaholiya** [comment]
yes, above code generates an error.

**Comment by kevin-hirsch** [comment]
Ok, strange. So you'll probably have to change all the `typealias` because should not be convertible to Objective-C, thus the variable of type of a `typealias` is not convertible to Objective-C.

So for the typealias
```swift
public typealias Closure = () -> Void
```
Just search `Closure` in the code and replace by `() -> Void`.
Same for
```swift
public typealias SelectionClosure = (Index, String) -> Void
public typealias ConfigurationClosure = (Index, String) -> String
```
Then build your project, you should now have the `dropDown.selectionAction` available in Objective-C, along with `cancelAction`, ...

**Comment by markedwardmurray** [comment]
I didn't have any trouble with the Closure syntax bridging to Objective-C. Perhaps Xcode 7.3 can handle backwards-bridging the typealiases now?
